### ISSUE TITLE
Question about function close_form_emb_regzero

### ISSUE THREAD

**Issue by yaohui120** [CharlesGong12/RECE#2]
In  the function close_form_emb_regzero in RECE-main/utils/embedding_calculation/close_form_emb.py, I couldn't understand why you reset the parameters. It seems that there is no difference before and after the replacement.

**Comment by CharlesGong12** [comment]
Hi, thanks for your attention.

The resetting codes are borrowed from [UCE](https://github.com/rohitgandikota/unified-concept-editing/blob/f7222e63fc01fee426a61a90c0215edacbe983b6/train-scripts/train_erase.py#L196) so I didn't make any changes. In the [issues of UCE](https://github.com/rohitgandikota/unified-concept-editing/issues/13#issuecomment-1907346045), the author explained that the resetting codes can be deleted in erasing code but they have some significance in debiasing code so they are reserved. You can check the paper and code of UCE.

Any further questions, contact me~^^

**Comment by yaohui120** [comment]
Thank you for your answer!!!
