### ISSUE TITLE
The target_ckpt of nudity.sh

### ISSUE THREAD

**Issue by LucidStephen** [CharlesGong12/RECE#4]
https://github.com/CharlesGong12/RECE/blob/c2af080ea045c33911dd7471055547d1b0e9ff95/scripts/nudity.sh#L7

Hello authors, I want to understand what this PT file is and how to obtain it to reproduce results similar to yours.

**Comment by CharlesGong12** [comment]
Hi, the target_ckpt is the result of [UCE](https://github.com/rohitgandikota/unified-concept-editing), and the related code is also included in our repo, `erase_methods/train_uce.py`. In Algorithm 1 of our paper, we mentioned we first erase with UCE and then we loop our derivation-editing procedure.

**Comment by LucidStephen** [comment]
Thank you for your answer!  Is it possible to run train_uce.py directly without specifying additional parameters? If that's the case, the resulting pt file I obtained after running the script is named 'erased-nudity-towards_uncond-preserve_false-sd_1_4-method_replace-erase_1-preserve_1.0-lamb_0.5-1-1.0.pt'. I would like to confirm if the settings used are correct as your script's setting.

**Comment by CharlesGong12** [comment]
Hi!
Yes, the default settings are right.
