### ISSUE TITLE
preserve_concepts

### ISSUE THREAD

**Issue by xszz666** [CharlesGong12/RECE#6]
你好，我想问一下预训练好的模型里面，您在训练church对应的.pt时，preserve_concepts如何选择呢，以及preserve_scale和erase_scale的选择，感谢解答

**Comment by CharlesGong12** [comment]
您好呀，
您是指UCE得到的ckpt吗，我们直接用的UCE的默认超参，您可以看一下UCE GitHub的脚本。如果您是指我们huggingface里的模型权重，我们用的就是`scripts/object.sh`中的命令，您提到的这些都是用的默认值。
Hi,
Do you mean the ckpt that UCE gets? We used the default hyperparameters from UCE directly and you can look at the scripts of UCE's github repo. If you mean the model weights in our huggingface page, we use the command in `scripts/object.sh`. These you mentioned are using default values.

**Comment by xszz666** [comment]
感谢解答
